USE_CAMERA_STUB := true

LOCAL_PATH := device/lava/irsx1
BOARD_VENDOR := lava


TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := armv7
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true



BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x82000000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_BOOTLOADER_BOARD_NAME := irsx1
TARGET_DEVICE := irsx1


TW_MAX_BRIGHTNESS := 255
TW_NO_SCREEN_BLANK := true

BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_23x41.h\"


TARGET_RECOVERY_FSTAB := device/lava/irsx1/recovery.fstab


TARGET_USERIMAGES_USE_EXT4 := true

BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_ALSA_AUDIO := false

TARGET_PREBUILT_KERNEL := device/lava/irsx1/kernel
TARGET_PREBUILT_RECOVERY_KERNEL := device/lava/irsx1/kernel
TARGET_RECOVERY_FSTAB := device/lava/irsx1/recovery.fstab


BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_HAS_NO_REAL_SDCARD := true
TARGET_RECOVERY_INITRC := device/lava/irsx1/init.rc
# Use this flag if the board has a ext4 partition larger than 2gb
#BOARD_HAS_LARGE_FILESYSTEM := true



#twrp
DEVICE_RESOLUTION :=  480x854
RECOVERY_GRAPHICS_USE_LINELENGTH := true
RECOVERY_TOUCHSCREEN_FLIP_X := true
TW_FLASH_FROM_STORAGE := true 
TW_INTERNAL_STORAGE_PATH := "/storage/sdcard2" 
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard2"
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_NO_USB_STORAGE := true
RECOVERY_SDCARD_ON_DATA := true
TW_MAX_BRIGHTNESS := 255
TW_BRIGHTNESS_PATH := "/sys/devices/platform/pwm-backlight.0/backlight/pwm-backlight.0/brightness"
#BOARD_VOLD_MAX_PARTITIONS := 16

#Use these flags to correct aroma one at a time
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
#TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
#TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"

